import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import './globals.css';

import { Toaster } from '@/components/ui/sonner';

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin'],
  weight: ['400', '500', '700']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoMono.variable} antialiased`}>
        <div className="min-h-screen bg-gray-100">
          <div className="container mx-auto px-4 py-8">
            <h1 className="text-3xl font-bold text-center mb-6 text-black">
              Account Management
            </h1>
            <div className="max-w-sm mx-auto">{children}</div>
            <Toaster
              toastOptions={{
                classNames: {
                  toast: 'font-mono text-sm',
                  title: 'font-mono text-sm',
                  description: 'font-mono text-xs'
                }
              }}
              position="top-center"
            />
          </div>
        </div>
      </body>
    </html>
  );
}
